import { NextRequest, NextResponse } from 'next/server';
import { toJsStringLiteral, escapeHtml } from '@/lib/social/html-escape';
import { verifyState } from '@/lib/social/oauth-state';
import { auth } from '@/lib/auth/config';
import { supabaseAdmin as supabase } from '@/lib/db/supabase';

// GET /api/social/callback?platform=xxx&code=xxx&state=xxx
// OAuth callback handler for all social platforms
export async function GET(req: NextRequest) {
    try {
          const { searchParams } = new URL(req.url);
          const platform = searchParams.get('platform');
          const code = searchParams.get('code');
          const state = searchParams.get('state');
          const error = searchParams.get('error');

      if (error) {
              return redirectWithMessage('error', `Connexion refusee: ${error}`);
      }

      if (!platform || !code) {
              return redirectWithMessage('error', 'Parametres manquants');
      }

      // Validation du `state` (protection CSRF).
      //
      // Le `userId` lu ici designe le compte Studiio auquel le compte social
      // va etre rattache. Il etait pris TEL QUEL dans un parametre d'URL :
      // appeler cette route avec `state=<id victime>:0:x` rattachait le compte
      // social de l'appelant au compte Studiio de la victime.
      //
      // On exige donc maintenant la signature posee par /api/social/connect.
      // Un `state` herite (3 segments, non signe) est refuse : l'accepter
      // laisserait la faille entiere, un attaquant n'ayant qu'a omettre la
      // signature. Seul un flux OAuth deja en vol au moment du deploiement
      // peut tomber sur ce refus — l'utilisateur relance « Connecter ».
      const verified = verifyState(state);
      if (!verified.valid || !verified.userId) {
              console.warn('[SOCIAL_CALLBACK] state refuse', { platform, reason: verified.reason });
              return redirectWithMessage('error', 'State invalide');
      }
      const userId = verified.userId;

      let tokenData: { accessToken: string; refreshToken?: string; accountId: string; accountName: string; expiresAt?: string };

      switch (platform) {
        case 'instagram':
        case 'facebook':
                  tokenData = await exchangeMetaToken(code, platform);
                  break;
        case 'tiktok':
                  tokenData = await exchangeTikTokToken(code);
                  break;
        case 'youtube':
                  tokenData = await exchangeYouTubeToken(code);
                  break;
        default:
                  return redirectWithMessage('error', `Plateforme non supportee: ${platform}`);
      }

      // Save to database.
      // Note : `userId` here comes from state (generated by /api/social/connect).
      // The auth fix (PR #167) may have shifted user.id values, so the state
      // may carry a stale id. Cross-check with the current session and try
      // the session id as a fallback if the state-userId insert fails on
      // foreign-key.
      const sessionForCallback = await auth();
      const sessionUserId = sessionForCallback?.user?.id;
      const candidates = [
        userId,
        ...(sessionUserId && sessionUserId !== userId ? [sessionUserId] : []),
      ];
      console.log('[SOCIAL_CALLBACK] save attempt', {
        platform,
        stateUserId: userId,
        sessionUserId: sessionUserId || null,
        candidatesCount: candidates.length,
      });

      const now = new Date().toISOString();
      let dbError: any = null;
      let savedWithUserId: string | null = null;
      for (const candidate of candidates) {
        const { error: err } = await supabase
          .from('social_accounts')
          .upsert(
            {
              user_id: candidate,
              platform,
              account_id: tokenData.accountId,
              account_name: tokenData.accountName,
              access_token: tokenData.accessToken,
              refresh_token: tokenData.refreshToken || null,
              expires_at: tokenData.expiresAt || null,
              connected: true,
              updated_at: now,
            },
            { onConflict: 'user_id,platform' },
          );
        if (!err) {
          dbError = null;
          savedWithUserId = candidate;
          break;
        }
        dbError = err;
        console.error('[SOCIAL_CALLBACK] upsert failed with user_id=' + candidate, {
          code: (err as any).code,
          message: (err as any).message,
          details: (err as any).details,
          hint: (err as any).hint,
        });
      }

      if (dbError) {
        const detail = `${(dbError as any).code || '?'} ${(dbError as any).message || ''}${(dbError as any).hint ? ' — hint: ' + (dbError as any).hint : ''}`.trim();
        return redirectWithMessage('error', `Erreur de sauvegarde: ${detail}`);
      }
      console.log('[SOCIAL_CALLBACK] saved successfully', { platform, savedWithUserId });

      return redirectWithMessage('success', `${platform} connecte avec succes!`);
    } catch (error: any) {
          const msg = error?.message || String(error) || 'Erreur inconnue';
          const stack = error?.stack ? error.stack.split('\n').slice(0, 3).join(' | ') : '';
          console.error('[SOCIAL_CALLBACK_ERROR]', { platform: req.nextUrl.searchParams.get('platform'), msg, stack });
          return redirectWithMessage('error', msg + (stack ? ' — ' + stack : ''));
    }
}

function redirectWithMessage(type: string, message: string): NextResponse {
    const isSuccess = type === 'success';
    // Deux contextes, deux echappements — les confondre est une XSS.
    //
    // L'ancien `replace(/'/g, "\\'")` ne tenait pas : un antislash final
    // (`...\`) devenait `...\'` et fermait la chaine JS, permettant d'injecter
    // du script. Or `message` transporte `error_description`, un parametre
    // d'URL entierement controle par l'appelant.
    const jsMessage = toJsStringLiteral(message);
    const safeMessage = escapeHtml(message);
    const html = isSuccess
      ? `<!DOCTYPE html><html><head><title>Connexion reussie</title></head><body style="font-family:sans-serif;padding:40px;text-align:center">
<script>
  if (window.opener) {
    window.opener.postMessage({ type: 'social-oauth-success', message: ${jsMessage} }, '*');
  }
  setTimeout(() => window.close(), 800);
</script>
<p>✓ ${safeMessage}</p>
<p style="color:#888">Cette fenetre va se fermer automatiquement.</p>
</body></html>`
      : `<!DOCTYPE html><html><head><title>Erreur de connexion</title></head><body style="font-family:sans-serif;padding:40px;max-width:600px;margin:auto">
<h2 style="color:#c00">Echec de la connexion</h2>
<p style="background:#fee;padding:16px;border-radius:8px;border:1px solid #fcc"><strong>Detail :</strong> ${safeMessage}</p>
<p style="color:#555">Copiez le message ci-dessus et renvoyez-le pour diagnostic.</p>
<button onclick="window.close()" style="padding:10px 20px;background:#333;color:#fff;border:0;border-radius:6px;cursor:pointer">Fermer</button>
<script>
  if (window.opener) {
    window.opener.postMessage({ type: 'social-oauth-error', message: ${jsMessage} }, '*');
  }
</script>
</body></html>`;
    return new NextResponse(html, {
      headers: { 'Content-Type': 'text/html; charset=utf-8', 'X-Content-Type-Options': 'nosniff' },
    });
}

// ══════════════════════════════════════════════════════════════
// TOKEN EXCHANGE FUNCTIONS
// ══════════════════════════════════════════════════════════════

async function exchangeMetaToken(code: string, platform: string) {
    const appId = platform === 'instagram'
      ? process.env.META_INSTAGRAM_APP_ID || process.env.FACEBOOK_CLIENT_ID
          : process.env.FACEBOOK_CLIENT_ID;
    const appSecret = platform === 'instagram'
      ? process.env.META_INSTAGRAM_APP_SECRET || process.env.FACEBOOK_CLIENT_SECRET
          : process.env.FACEBOOK_CLIENT_SECRET;
    const redirectUri = `${process.env.NEXTAUTH_URL || process.env.NEXT_PUBLIC_APP_URL}/api/social/callback?platform=${platform}`;

  // Exchange code for short-lived token
  const tokenRes = await fetch(
        `https://graph.facebook.com/v24.0/oauth/access_token?` +
        `client_id=${appId}&client_secret=${appSecret}&code=${code}&redirect_uri=${encodeURIComponent(redirectUri)}`
      );
    const tokenData = await tokenRes.json();

  if (tokenData.error) {
        throw new Error(tokenData.error.message);
  }

  // Exchange for long-lived token (60 days)
  const longTokenRes = await fetch(
        `https://graph.facebook.com/v24.0/oauth/access_token?` +
        `grant_type=fb_exchange_token&client_id=${appId}&client_secret=${appSecret}&fb_exchange_token=${tokenData.access_token}`
      );
    const longTokenData = await longTokenRes.json();
    let accessToken = longTokenData.access_token || tokenData.access_token;

  // Get account info
  let accountId = '';
    let accountName = '';

  if (platform === 'instagram') {
        // Get Instagram Business Account ID via Facebook Pages
        // User may have multiple pages — iterate all to find the one with an IG Business Account
      const pagesRes = await fetch(
              `https://graph.facebook.com/v24.0/me/accounts?fields=id,name,access_token,instagram_business_account&access_token=${accessToken}`
            );
        const pagesData = await pagesRes.json();
        const pages = pagesData.data || [];

        console.log(`[OAuth/Instagram] Found ${pages.length} Facebook Pages:`, pages.map((p: any) => ({ id: p.id, name: p.name, ig: p.instagram_business_account?.id })));

        // Find the first page that has an Instagram Business Account linked
        let igAccountId: string | null = null;
        let pageAccessToken: string | null = null;
        let linkedPageId: string | null = null;
        let fallbackPageName = pages[0]?.name || 'instagram_user';

        for (const page of pages) {
          if (page.instagram_business_account?.id) {
            igAccountId = page.instagram_business_account.id;
            pageAccessToken = page.access_token || null;
            linkedPageId = page.id;
            fallbackPageName = page.name;
            console.log(`[OAuth/Instagram] Found IG Business Account ${igAccountId} on page "${page.name}" (page_id: ${page.id})`);
            break;
          }
        }

        // If no page has IG Business Account, try querying each page individually
        // (fields=instagram_business_account sometimes omits it depending on app review status)
        if (!igAccountId) {
          for (const page of pages) {
            const pageToken = page.access_token || accessToken;
            const igRes = await fetch(
              `https://graph.facebook.com/v24.0/${page.id}?fields=instagram_business_account&access_token=${pageToken}`
            );
            const igData = await igRes.json();
            if (igData.instagram_business_account?.id) {
              igAccountId = igData.instagram_business_account.id;
              pageAccessToken = page.access_token || null;
              linkedPageId = page.id;
              fallbackPageName = page.name;
              console.log(`[OAuth/Instagram] Found IG Business Account ${igAccountId} on page "${page.name}" (individual query)`);
              break;
            }
          }
        }

        if (!igAccountId) {
          // Hard fail — storing the wrong ID causes Graph API error #100 "does not exist"
          console.error('[OAuth/Instagram] No Instagram Business Account found on any Page. User must (1) have a Business/Creator IG account, (2) link it to a FB Page they admin, (3) grant instagram_basic + instagram_content_publish.');
          throw new Error('Aucun compte Instagram Business trouvé. Vérifiez que votre compte IG est en mode Business/Creator et lié à une Page Facebook que vous administrez.');
        }
        if (!pageAccessToken) {
          console.error('[OAuth/Instagram] Found IG Business Account but no Page Access Token returned. Check pages_show_list scope.');
          throw new Error('Token de page Facebook manquant. Vérifiez les permissions pages_show_list et pages_read_engagement.');
        }

        accountId = igAccountId;          // IG Business Account ID (17841...)
        accessToken = pageAccessToken;    // Page Access Token (required by Graph API for IG publishing)
        console.log(`[OAuth/Instagram] Stored account_id=${accountId} with page_access_token from page ${linkedPageId}`);

        // Get IG username from the Instagram Business Account
        const igInfoRes = await fetch(
          `https://graph.facebook.com/v24.0/${accountId}?fields=username,name&access_token=${accessToken}`
        );
        const igInfo = await igInfoRes.json();
        accountName = igInfo.username || igInfo.name || fallbackPageName;
        console.log(`[OAuth/Instagram] IG username resolved: "${accountName}" (from account ${accountId})`);
  } else {
        // Facebook Page — we need the PAGE access token and PAGE ID to publish
        // The user-level token cannot post to Pages; we need a Page Access Token
        const pagesRes = await fetch(
              `https://graph.facebook.com/v24.0/me/accounts?fields=id,name,access_token&access_token=${accessToken}`
            );
        const pagesData = await pagesRes.json();
        const pages = pagesData.data || [];

        console.log(`[OAuth/Facebook] Found ${pages.length} Facebook Pages:`, pages.map((p: any) => ({ id: p.id, name: p.name })));

        if (pages.length > 0) {
          // Use the first page's credentials (most users have one page)
          const page = pages[0];
          if (!page.access_token) {
            console.error('[OAuth/Facebook] Page found but no Page Access Token returned. Check pages_show_list scope.');
            throw new Error('Token de page Facebook manquant. Vérifiez les permissions pages_show_list et pages_manage_posts.');
          }
          accountId = page.id;              // Page ID (not user ID!) — used as /{page_id}/videos target
          accountName = page.name || 'facebook_page';
          accessToken = page.access_token;  // Page Access Token — required to publish to a Page
          console.log(`[OAuth/Facebook] Using Page Access Token for page "${page.name}" (page_id: ${page.id})`);
        } else {
          // Hard fail — no Page means publishing is impossible
          console.error('[OAuth/Facebook] No Facebook Pages found on this account.');
          throw new Error('Aucune Page Facebook trouvée sur ce compte. Vous devez administrer au moins une Page Facebook pour publier.');
        }
  }

  const expiresAt = longTokenData.expires_in
      ? new Date(Date.now() + longTokenData.expires_in * 1000).toISOString()
        : new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(); // 60 days default

  return { accessToken, accountId, accountName, expiresAt };
}

async function exchangeTikTokToken(code: string) {
    const clientKey = process.env.TIKTOK_CLIENT_KEY;
    const clientSecret = process.env.TIKTOK_CLIENT_SECRET;
    const redirectUri = `${process.env.NEXTAUTH_URL || process.env.NEXT_PUBLIC_APP_URL}/api/social/callback/tiktok`;

  const tokenRes = await fetch('https://open.tiktokapis.com/v2/oauth/token/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
                client_key: clientKey || '',
                client_secret: clientSecret || '',
                code,
                grant_type: 'authorization_code',
                redirect_uri: redirectUri,
        }),
  });

  const tokenData = await tokenRes.json();

  if (tokenData.error) {
        throw new Error(tokenData.error_description || tokenData.error);
  }

  return {
        accessToken: tokenData.access_token,
        refreshToken: tokenData.refresh_token,
        accountId: tokenData.open_id,
        accountName: `tiktok_${tokenData.open_id?.slice(0, 8)}`,
        expiresAt: tokenData.expires_in
          ? new Date(Date.now() + tokenData.expires_in * 1000).toISOString()
                : undefined,
  };
}

async function exchangeYouTubeToken(code: string) {
    const clientId = process.env.YOUTUBE_CLIENT_ID || process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.YOUTUBE_CLIENT_SECRET || process.env.GOOGLE_CLIENT_SECRET;
    const redirectUri = `${process.env.NEXTAUTH_URL || process.env.NEXT_PUBLIC_APP_URL}/api/social/callback?platform=youtube`;

  const tokenRes = await fetch('https://oauth2.googleapis.com/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
                code,
                client_id: clientId || '',
                client_secret: clientSecret || '',
                redirect_uri: redirectUri,
                grant_type: 'authorization_code',
        }),
  });

  const tokenData = await tokenRes.json();

  if (tokenData.error) {
        throw new Error(tokenData.error_description || tokenData.error);
  }

  // Get channel inf
  const channelRes = await fetch(
        `https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true`,
    { headers: { Authorization: `Bearer ${tokenData.access_token}` } }
      );
    const channelData = await channelRes.json();
    const channel = channelData.items?.[0];

  return {
        accessToken: tokenData.access_token,
        refreshToken: tokenData.refresh_token,
        accountId: channel?.id || 'unknown',
        accountName: channel?.snippet?.title || 'youtube_user',
        expiresAt: tokenData.expires_in
          ? new Date(Date.now() + tokenData.expires_in * 1000).toISOString()
                : undefined,
  };
}
